doctrine:
  dbal:
    types:
      datetime: UbeeDev\LibBundle\Doctrine\DBAL\Types\DateTimeType
      date: UbeeDev\LibBundle\Doctrine\DBAL\Types\DateType
      money: UbeeDev\LibBundle\Doctrine\DBAL\Types\MoneyType
      email: UbeeDev\LibBundle\Doctrine\DBAL\Types\EmailType
      name: UbeeDev\LibBundle\Doctrine\DBAL\Types\NameType
      url: UbeeDev\LibBundle\Doctrine\DBAL\Types\UrlType
      htmlName: UbeeDev\LibBundle\Doctrine\DBAL\Types\HtmlNameType

when@test:
  doctrine:
    dbal:
      connections:
        default:
          # "TEST_TOKEN" is typically set by ParaTest
          dbname_suffix: '_test%env(TEST_TOKEN)%'