doctrine:
  dbal:
    types:
      datetime: Khalil1608\LibBundle\Doctrine\DBAL\Types\DateTimeType
      date: Khalil1608\LibBundle\Doctrine\DBAL\Types\DateType
      money: Khalil1608\LibBundle\Doctrine\DBAL\Types\MoneyType
      email: Khalil1608\LibBundle\Doctrine\DBAL\Types\EmailType
      name: Khalil1608\LibBundle\Doctrine\DBAL\Types\NameType
      url: Khalil1608\LibBundle\Doctrine\DBAL\Types\UrlType
      htmlName: Khalil1608\LibBundle\Doctrine\DBAL\Types\HtmlNameType

when@test:
  doctrine:
    dbal:
      connections:
        default:
          # "TEST_TOKEN" is typically set by ParaTest
          dbname_suffix: '_test%env(TEST_TOKEN)%'
          use_savepoints: true