framework:
  session:
    cookie_lifetime: 0 # on browser close
    gc_maxlifetime: 14000 # 4 hours in seconds
    handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
    name: SESSID
    cookie_secure: true
    cookie_httponly: true
    
when@test: &framework_test
  framework:
    test: true
    
when@dev: *framework_test
