old_sound_rabbit_mq:
  connections:
    default:
      host:     '%env(RABBITMQ_HOST)%'
      port:     5672
      user:     '%env(RABBITMQ_USER)%'
      password: '%env(RABBITMQ_PASSWORD)%'
      vhost:    '/'
      lazy:     true
  producers:
    error:
      connection: default
      exchange_options: {name: 'error-exchange', type: direct}
      queue_options:    {name: 'error-queue'}
    send_email:
      connection:       default
      exchange_options: {name: 'send_email', type: x-delayed-message, arguments:{'x-delayed-type': ['S', 'direct']}}
      queue_options:    {name: 'send_email'}
    send_bulk_email:
      connection:       default
      exchange_options: {name: 'send_bulk_email', type: x-delayed-message, arguments:{'x-delayed-type': ['S', 'direct']}}
      queue_options:    {name: 'send_bulk_email'}
    send_slack_notification:
      connection:       default
      exchange_options: {name: 'send_slack_notification', type: x-delayed-message, arguments:{'x-delayed-type': ['S', 'direct']}}
      queue_options:    {name: 'send_slack_notification'}
    compress_pdf:
      connection: default
      exchange_options: { name: 'compress_pdf', type: direct }
      queue_options: { name: 'compress_pdf' }
  
  
  consumers:
    error:
      connection: default
      exchange_options: {name: 'error-exchange', type: direct}
      queue_options:    {name: 'error-queue'}
      callback: UbeeDev\LibBundle\Consumer\ErrorConsumer
    send_email:
      connection:       default
      exchange_options: {name: 'send_email', type: x-delayed-message, arguments:{'x-delayed-type': ['S', 'direct']}}
      queue_options:    {name: 'send_email'}
      callback:         UbeeDev\LibBundle\Consumer\EmailConsumer
    send_bulk_email:
      connection:       default
      exchange_options: {name: 'send_bulk_email', type: x-delayed-message, arguments:{'x-delayed-type': ['S', 'direct']}}
      queue_options:    {name: 'send_bulk_email'}
      callback:         UbeeDev\LibBundle\Consumer\BulkEmailConsumer
    send_slack_notification:
      connection:       default
      exchange_options: {name: 'send_slack_notification', type: x-delayed-message, arguments:{'x-delayed-type': ['S', 'direct']}}
      queue_options:    {name: 'send_slack_notification'}
      callback:         UbeeDev\LibBundle\Consumer\SlackNotificationConsumer
    compress_pdf:
      connection: default
      exchange_options: { name: 'compress_pdf', type: direct }
      queue_options: { name: 'compress_pdf' }
      callback: UbeeDev\LibBundle\Consumer\CompressPdfConsumer